stages:
    - testing
    - coverage
    - reports

run_tests:
    stage: testing
    tags:
    - docker
    image: python:3.11-slim
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - pytest --alluredir=./allure-results
    allow_failure: true
    artifacts:
        when: always
        paths:
            - ./allure-results
            - ./swagger-coverage-output

allure:
    stage: reports
    tags:
        - docker
    image: sergeymazanik/chrome_allure_python
    script:
        - allure generate -c ./allure-results -o ./allure-report
    artifacts:
        paths:
            - ./allure-results
            - ./allure-report
        expire_in: 1 days
    rules:
        - when: always

pages:
    stage: reports
    needs: ["allure"]
    script:
        - mkdir public
        - mv ./allure-report/* public
    artifacts:
        paths:
            - public
    rules:
        - when: always

coverage:
    stage: coverage
    tags:
        - docker
    image: adoptopenjdk/openjdk11
    before_script:
        - apt-get update && apt-get install -y wget unzip
        - wget https://github.com/viclovsky/swagger-coverage/releases/download/1.5.0/swagger-coverage-1.5.0.zip
        - unzip swagger-coverage-1.5.0.zip
    script:
        - ./swagger-coverage-commandline-1.5.0/bin/swagger-coverage-commandline -s http://5.63.153.31:5051/swagger/Account/swagger.json -i swagger-coverage-output
        - cp swagger-coverage-report.html swagger-coverage-report-dm-api-account.html
        - rm swagger-coverage-report.html
    allow_failure: true
    artifacts:
        when: always
        paths:
            - ./swagger-coverage-report-dm-api-account.html
        expire_in: 1 days

send_coverage:
    stage: coverage
    needs: ["coverage"]
    tags:
        - docker
    image: python:3.11-slim
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - ls -la
        - python -m packages.notifier.bot
    allow_failure: true